remote_theme: Volga/beautiful-jekyll
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
title: ТОРТЫ ОТ АНЕЧКИ
description: Вкуснейшие торты, капкейки, кейкпопсы, эклеры, макаронс, пряники на заказ - Москва, СВАО - Медведково, Бабушкинская, Свиблово, Бибирево, Алтуфьево, Отрадное
avatar: "/img/avatar-icon.png"
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"