remote_theme: Volga/beautiful-jekyll
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
title: ТОРТЫ ОТ АНЕЧКИ
description: Вкуснейшие торты, капкейки, кейкпопсы, эклеры, макаронс, пряники на заказ - Москва, СВАО - Медведково, Бабушкинская, Свиблово, Бибирево, Алтуфьево, Отрадное
avatar: "/img/avatar-icon.png"